const LESSONS={
  huruf:{title:"Kenal Huruf",world:"🌳 HUTAN HURUF",header:"Hutan Huruf",mission:"🎯 MISI: KENAL HURUF",instruction:"Tekan huruf yang sama seperti kartu di bawah.",type:"letter",rounds:10,badge:"alphabet-master",items:"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")},
  kata:{title:"Kata Pendek",world:"🏡 DESA KATA",header:"Desa Kata",mission:"🧩 MISI: KATA PENDEK",instruction:"Ketik satu kata yang muncul di kartu.",type:"word",rounds:10,badge:"word-explorer",items:["buku","meja","tas","guru","bola","rumah","makan","minum","teman","sekolah","kucing","pensil","kelas","pagi"]},
  angka:{title:"Kenal Angka",world:"🏝️ PULAU ANGKA",header:"Pulau Angka",mission:"🔢 MISI: KENAL ANGKA",instruction:"Ketik angka yang sama seperti kartu di bawah.",type:"number",rounds:10,badge:"number-friend",items:["1","2","3","4","5","6","7","8","9","0","10","12","15","20"]},
  kalimat:{title:"Kalimat Mini",world:"🏰 KASTIL KALIMAT",header:"Kastil Kalimat",mission:"✏️ MISI: KALIMAT MINI",instruction:"Ketik kalimat pendek di kartu dengan pelan dan teliti.",type:"sentence",rounds:6,badge:"sentence-hero",items:["Saya suka belajar.","Nama saya hebat.","Saya duduk rapi.","Saya suka komputer.","Hari ini saya belajar.","Saya mengetik pelan.","Saya bisa mencoba lagi.","Guru membantu saya."]}
};
const BADGES={"first-step":{icon:"🌟",name:"Langkah Pertama"},"alphabet-master":{icon:"🔤",name:"Master A–Z"},"word-explorer":{icon:"📚",name:"Penjelajah Kata"},"number-friend":{icon:"🔢",name:"Sahabat Angka"},"sentence-hero":{icon:"✏️",name:"Pahlawan Kalimat"},"combo-five":{icon:"🔥",name:"Combo 5"}};
const KEYBOARD_ROWS=["1234567890".split(""),"QWERTYUIOP".split(""),"ASDFGHJKL".split(""),"ZXCVBNM".split("")];
const XP_PER_LEVEL=500;
const STORAGE_KEY="ketik100-adventure-v12";

const params=new URLSearchParams(location.search);
const requested=params.get("mode");
const currentLesson=LESSONS[requested]?requested:"huruf";
const lesson=LESSONS[currentLesson];

const el=id=>document.getElementById(id);
const typingInput=el("typingInput"),targetLine=el("targetLine"),targetCard=el("targetCard"),targetHint=el("targetHint"),feedback=el("feedbackMessage");
const startBtn=el("startBtn"),restartBtn=el("restartBtn"),scoreStat=el("scoreStat"),comboStat=el("comboStat"),starStat=el("starStat"),roundLabel=el("roundLabel"),progressPercent=el("progressPercent"),progressBar=el("progressBar"),chestMilestone=el("chestMilestone");
const rewardPop=el("rewardPop"),keyboard=el("keyboard"),countdownOverlay=el("countdownOverlay"),countdownNumber=el("countdownNumber"),countdownText=el("countdownText");
const chestOverlay=el("chestOverlay"),openChestBtn=el("openChestBtn"),continueChestBtn=el("continueChestBtn"),chestEmoji=el("chestEmoji"),chestReward=el("chestReward"),chestRewardTitle=el("chestRewardTitle"),chestRewardXp=el("chestRewardXp");
const finishOverlay=el("finishOverlay"),finishScore=el("finishScore"),finishStars=el("finishStars"),finishXp=el("finishXp"),finishMessage=el("finishMessage"),finishLevelText=el("finishLevelText"),finishXpBar=el("finishXpBar");
const badgeToast=el("badgeToast"),badgeToastIcon=el("badgeToastIcon"),badgeToastName=el("badgeToastName"),soundToggle=el("soundToggle"),kiboMini=el("kiboMini"),kiboSpeech=el("kiboGameSpeech"),sessionXpEl=el("sessionXp"),miniXpBar=el("miniXpBar"),levelText=el("levelText"),headerLevel=el("headerLevel");

let queue=[],currentRound=0,score=0,combo=0,stars=0,correct=0,sessionXp=0,mistakesThisRound=0;
let gameActive=false,locked=false,chestOpened=false,chestFinishesGame=false,countdownTimer=null,advanceTimer=null,badgeTimer=null;
let soundEnabled=storageGet("ketik100-sound")!=="off";
let adventure=loadAdventure();

function storageGet(key){try{return localStorage.getItem(key)}catch{return null}}
function storageSet(key,value){try{localStorage.setItem(key,value)}catch{}}
function loadAdventure(){const fallback={xp:0,totalStars:0,totalCorrect:0,chests:0,badges:[],completed:[]};try{const saved=JSON.parse(storageGet(STORAGE_KEY)||"null");if(!saved||typeof saved!=="object")return fallback;return{xp:Math.max(0,Number(saved.xp)||0),totalStars:Math.max(0,Number(saved.totalStars)||0),totalCorrect:Math.max(0,Number(saved.totalCorrect)||0),chests:Math.max(0,Number(saved.chests)||0),badges:Array.isArray(saved.badges)?saved.badges.filter(id=>BADGES[id]):[],completed:Array.isArray(saved.completed)?saved.completed.filter(id=>LESSONS[id]):[]}}catch{return fallback}}
function saveAdventure(){storageSet(STORAGE_KEY,JSON.stringify(adventure))}
function levelInfo(xp=adventure.xp){const safe=Math.max(0,Number(xp)||0);return{level:Math.floor(safe/XP_PER_LEVEL)+1,current:safe%XP_PER_LEVEL,percent:((safe%XP_PER_LEVEL)/XP_PER_LEVEL)*100}}
function renderLevel(){const info=levelInfo();headerLevel.textContent=info.level;levelText.textContent=`Level ${info.level} • ${info.current}/${XP_PER_LEVEL} XP`;miniXpBar.style.width=`${info.percent}%`;sessionXpEl.textContent=`+${sessionXp} XP`}
function setKibo(text,mood=""){kiboSpeech.textContent=text;kiboMini.className=`kibo-mini${mood?` ${mood}`:""}`}
function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildQueue(){const pool=shuffle(lesson.items);if(pool.length>=lesson.rounds)return pool.slice(0,lesson.rounds);const result=[];while(result.length<lesson.rounds)result.push(...shuffle(pool));return result.slice(0,lesson.rounds)}
function currentTarget(){return String(queue[currentRound]??lesson.items[0])}
function normalize(value){return String(value).trim().replace(/\s+/g," ").toLocaleLowerCase("id-ID")}
function clearTimers(){if(countdownTimer)clearTimeout(countdownTimer);if(advanceTimer)clearTimeout(advanceTimer);if(badgeTimer)clearTimeout(badgeTimer);countdownTimer=advanceTimer=badgeTimer=null}
function setFeedback(text,type=""){feedback.textContent=text;feedback.className=`feedback-message${type?` ${type}`:""}`}
function speak(text){if(!soundEnabled||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="id-ID";u.rate=.82;u.pitch=1.05;window.speechSynthesis.speak(u)}
function speakTarget(){const target=currentTarget();if(lesson.type==="letter")speak(`Ketik huruf ${target}`);else if(lesson.type==="number")speak(`Ketik angka ${target}`);else if(lesson.type==="word")speak(`Ketik kata ${target}`);else speak(`Ketik kalimat. ${target}`)}

function renderKeyboard(){keyboard.innerHTML="";KEYBOARD_ROWS.flat().forEach(key=>{const k=document.createElement("span");k.className="key";k.dataset.key=key.toLowerCase();k.textContent=key;keyboard.appendChild(k)});const space=document.createElement("span");space.className="key space";space.dataset.key=" ";space.textContent="SPASI";keyboard.appendChild(space)}
function updateKeyboardHint(){keyboard.querySelectorAll(".key.active").forEach(k=>k.classList.remove("active"));if(!gameActive||locked)return;const target=currentTarget();const typed=typingInput.value;const next=target[typed.length]??target[0]??"";const key=keyboard.querySelector(next===" "?'[data-key=" "]':`[data-key="${CSS.escape(next.toLowerCase())}"]`);if(key)key.classList.add("active")}
function renderTarget(){const target=currentTarget();targetLine.textContent=target;targetLine.className="target-line";if(lesson.type==="word")targetLine.classList.add("word");if(lesson.type==="sentence")targetLine.classList.add("sentence");if(lesson.type==="letter")targetHint.textContent=`Cari huruf ${target} di keyboard`;else if(lesson.type==="number")targetHint.textContent=`Cari angka ${target} di keyboard`;else if(lesson.type==="word")targetHint.textContent=`${target.length} huruf • ketik pelan-pelan`;else targetHint.textContent="Baca dulu, lalu ketik sedikit demi sedikit";typingInput.maxLength=lesson.type==="letter"?1:Math.max(target.length+5,20);typingInput.inputMode=lesson.type==="number"?"numeric":"text";updateKeyboardHint()}
function renderHud(){const done=Math.min(currentRound,lesson.rounds),pct=Math.round(done/lesson.rounds*100);scoreStat.textContent=score.toLocaleString("id-ID");comboStat.textContent=`${combo}🔥`;starStat.textContent=`${stars}⭐`;roundLabel.textContent=`Ronde ${Math.min(currentRound+1,lesson.rounds)} dari ${lesson.rounds}`;progressPercent.textContent=`${pct}%`;progressBar.style.width=`${pct}%`;const nextChest=correct<5?5:correct<10?10:null;chestMilestone.textContent=nextChest?`🎁 Peti di ${nextChest} benar`:"🏆 Menuju selesai"}

function unlockBadge(id){if(!BADGES[id]||adventure.badges.includes(id))return;adventure.badges.push(id);saveAdventure();const badge=BADGES[id];badgeToastIcon.textContent=badge.icon;badgeToastName.textContent=badge.name;badgeToast.hidden=false;badgeToast.classList.remove("show");void badgeToast.offsetWidth;badgeToast.classList.add("show");clearTimeout(badgeTimer);badgeTimer=setTimeout(()=>{badgeToast.hidden=true;badgeToast.classList.remove("show")},3000)}
function awardXp(amount){const n=Math.max(0,Math.round(Number(amount)||0));if(!n)return;const before=levelInfo().level;adventure.xp+=n;sessionXp+=n;const after=levelInfo().level;renderLevel();if(after>before){setKibo(`LEVEL UP! Sekarang kamu Level ${after}!`,"happy");createConfetti(28);speak(`Level naik. Sekarang level ${after}`)}}
function createConfetti(amount=18){if(window.matchMedia?.("(prefers-reduced-motion: reduce)").matches)return;const colors=["#ffd45f","#72e3b6","#8c7cff","#ff8f70","#65cce6"];for(let i=0;i<amount;i++){const p=document.createElement("i");p.className="confetti";p.style.left=`${10+Math.random()*80}%`;p.style.top=`${15+Math.random()*20}%`;p.style.background=colors[i%colors.length];p.style.animationDelay=`${Math.random()*.18}s`;document.body.appendChild(p);setTimeout(()=>p.remove(),1350)}}

function resetGame(){clearTimers();queue=buildQueue();currentRound=score=combo=stars=correct=sessionXp=mistakesThisRound=0;gameActive=false;locked=false;chestOpened=false;chestFinishesGame=false;typingInput.value="";typingInput.disabled=true;startBtn.hidden=false;finishOverlay.hidden=true;chestOverlay.hidden=true;targetCard.classList.remove("success","wrong");setFeedback("Tekan “Mulai Game” saat sudah siap.");setKibo("Aku siap membantu. Tekan “Mulai Game” ya!");renderTarget();renderHud();renderLevel()}
function runCountdown(){clearTimers();countdownOverlay.hidden=false;typingInput.disabled=true;startBtn.hidden=true;const steps=[{n:"3",t:"Siapkan tanganmu!"},{n:"2",t:"Lihat kartunya…"},{n:"1",t:"Cari tombolnya…"},{n:"GO!",t:"Ayo mulai!"}];let i=0;const step=()=>{const s=steps[i];countdownNumber.textContent=s.n;countdownText.textContent=s.t;countdownNumber.style.animation="none";void countdownNumber.offsetWidth;countdownNumber.style.animation="countPop .65s ease";speak(s.n==="GO!"?"Mulai":s.n);i++;if(i<steps.length)countdownTimer=setTimeout(step,700);else countdownTimer=setTimeout(beginRound,600)};step()}
function startGame(){resetGame();gameActive=true;queue=buildQueue();renderTarget();renderHud();setKibo("Petualangan dimulai! Aku ikut menemani.","happy");runCountdown()}
function beginRound(){countdownOverlay.hidden=true;chestOverlay.hidden=true;locked=false;mistakesThisRound=0;typingInput.value="";typingInput.disabled=false;targetCard.classList.remove("success","wrong");setFeedback("Lihat kartu, lalu ketik jawabannya.");setKibo(currentRound===0?"Ayo! Cari tombol yang sama.":"Bagus. Kita lanjut satu soal lagi!");renderTarget();typingInput.focus({preventScroll:true});speakTarget()}
function wrongAnswer(){if(locked)return;mistakesThisRound++;combo=0;renderHud();targetCard.classList.remove("wrong");void targetCard.offsetWidth;targetCard.classList.add("wrong");setFeedback("Hampir! Lihat kartunya lagi lalu coba sekali lagi.","warning");setKibo("Tidak apa-apa. Coba lagi pelan-pelan.","encourage");if(lesson.type==="letter"||lesson.type==="number"){locked=true;advanceTimer=setTimeout(()=>{typingInput.value="";locked=false;targetCard.classList.remove("wrong");updateKeyboardHint();typingInput.focus({preventScroll:true})},430)}}
function correctAnswer(){if(locked)return;locked=true;typingInput.disabled=true;correct++;combo++;stars++;const earnedScore=100+Math.min(combo*10,100),earnedXp=25+Math.min(combo*2,15);score+=earnedScore;adventure.totalCorrect++;adventure.totalStars++;awardXp(earnedXp);unlockBadge("first-step");if(combo>=5)unlockBadge("combo-five");saveAdventure();targetCard.classList.remove("wrong");targetCard.classList.add("success");rewardPop.textContent=`+${earnedScore} • +${earnedXp} XP`;rewardPop.classList.remove("show");void rewardPop.offsetWidth;rewardPop.classList.add("show");setFeedback(mistakesThisRound?"Yes! Ketemu juga. Bagus sudah mencoba lagi!":"Hebat! Jawabanmu benar!","success");setKibo(combo>=3?`Combo ${combo}! Keren sekali!`:"Benar! Bintang kita bertambah.","happy");renderHud();createConfetti(combo>=3?18:10);if(combo>=3)speak(`Hebat. Combo ${combo}`);advanceTimer=setTimeout(()=>{const isLast=currentRound+1>=lesson.rounds;if(correct%5===0){chestFinishesGame=isLast;openChestCheckpoint();return}if(isLast){currentRound++;finishGame();return}currentRound++;typingInput.value="";targetCard.classList.remove("success");renderHud();beginRound()},850)}
function evaluate(){if(!gameActive||locked)return;const target=currentTarget(),typed=typingInput.value;updateKeyboardHint();if(!typed){targetCard.classList.remove("wrong");setFeedback("Lihat kartu, lalu ketik jawabannya.");return}if(normalize(typed)===normalize(target)){correctAnswer();return}if(lesson.type==="letter"){wrongAnswer();return}const a=typed.toLocaleLowerCase("id-ID"),b=target.toLocaleLowerCase("id-ID");if(b.startsWith(a)){targetCard.classList.remove("wrong");setFeedback(lesson.type==="number"?"Bagus, lanjutkan angkanya.":"Bagus, lanjutkan sedikit lagi.")}else wrongAnswer()}

function openChestCheckpoint(){locked=true;typingInput.disabled=true;chestOpened=false;chestReward.hidden=true;continueChestBtn.hidden=true;chestEmoji.textContent="🧰";openChestBtn.hidden=false;openChestBtn.disabled=false;chestOverlay.hidden=false;setKibo("Wah! Kita menemukan peti hadiah!","happy");speak("Kamu menemukan peti hadiah. Ayo buka petinya.")}
function revealChest(){if(chestOpened)return;chestOpened=true;const bonusStars=Math.floor(Math.random()*4)+2,bonusXp=50;stars+=bonusStars;adventure.totalStars+=bonusStars;adventure.chests++;awardXp(bonusXp);saveAdventure();renderHud();chestEmoji.textContent="🎁";chestRewardTitle.textContent=`+${bonusStars} ⭐`;chestRewardXp.textContent=`+${bonusXp} XP`;chestReward.hidden=false;continueChestBtn.hidden=false;openChestBtn.hidden=true;createConfetti(30);setKibo("Hore! Hadiahnya sudah kita ambil.","happy");speak(`Hore. Kamu mendapat ${bonusStars} bintang dan ${bonusXp} XP.`)}
function continueAfterChest(){chestOverlay.hidden=true;currentRound++;typingInput.value="";targetCard.classList.remove("success");if(chestFinishesGame){chestFinishesGame=false;finishGame();return}renderHud();beginRound()}
function finishGame(){clearTimers();gameActive=false;locked=true;typingInput.disabled=true;if(!adventure.completed.includes(currentLesson)){adventure.completed.push(currentLesson);awardXp(100)}unlockBadge(lesson.badge);saveAdventure();progressBar.style.width="100%";progressPercent.textContent="100%";roundLabel.textContent=`Selesai • ${lesson.rounds} ronde`;chestMilestone.textContent="🏆 Dunia selesai";finishScore.textContent=score.toLocaleString("id-ID");finishStars.textContent=`${stars} ⭐`;finishXp.textContent=`+${sessionXp} XP`;const info=levelInfo();finishLevelText.textContent=`Level ${info.level} • ${info.current}/${XP_PER_LEVEL} XP`;finishXpBar.style.width=`${info.percent}%`;finishMessage.textContent=combo>=5?"Petualangan selesai dengan combo keren. Mau pecahkan skor lagi?":"Kamu berhasil menyelesaikan dunia ini. Setiap usaha membuat Kibo makin kuat!";const key=`ketik100-best-${currentLesson}`,best=Number(storageGet(key)||0);if(score>best)storageSet(key,String(score));setKibo("Dunia selesai! Aku bangga sama usahamu.","happy");createConfetti(42);finishOverlay.hidden=false;speak("Petualangan selesai. Hebat sekali!")}

el("headerWorld").textContent=lesson.header;el("worldLabel").textContent=lesson.world;el("practiceTitle").textContent=lesson.title;el("missionPill").textContent=lesson.mission;el("instruction").textContent=lesson.instruction;document.title=`Ketik100 — ${lesson.header}`;
renderKeyboard();resetGame();soundToggle.setAttribute("aria-pressed",String(soundEnabled));soundToggle.textContent=soundEnabled?"🔊":"🔇";
typingInput.addEventListener("input",evaluate);typingInput.addEventListener("paste",e=>{e.preventDefault();setFeedback("Untuk latihan, ketik sendiri ya. Fitur tempel dimatikan.","warning")});typingInput.addEventListener("keydown",e=>{if(e.key==="Enter")e.preventDefault()});
startBtn.addEventListener("click",startGame);restartBtn.addEventListener("click",startGame);el("playAgainBtn").addEventListener("click",startGame);openChestBtn.addEventListener("click",revealChest);continueChestBtn.addEventListener("click",continueAfterChest);el("speakTarget").addEventListener("click",speakTarget);
soundToggle.addEventListener("click",()=>{soundEnabled=!soundEnabled;storageSet("ketik100-sound",soundEnabled?"on":"off");soundToggle.setAttribute("aria-pressed",String(soundEnabled));soundToggle.textContent=soundEnabled?"🔊":"🔇";if(!soundEnabled&&"speechSynthesis" in window)window.speechSynthesis.cancel();else speak("Suara panduan aktif")});
window.addEventListener("beforeunload",clearTimers);
